image:
  # -- image repository
  repository: mikenye/readsb-protobuf
  # -- image tag
  tag: v4.0.3
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [application docs](https://flightaware.com/adsb/piaware/advanced_configuration) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

securityContext:
  # -- (bool) Privileged securityContext may be required if USB device is accessed directly through the host machine
  privileged: true

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  # -- Configure a hostPathMount to mount a USB device in the container.
  # @default -- See values.yaml
  usb:
    enabled: true
    type: hostPath
    hostPath: /dev/bus/usb/001/004
