controller:
  # -- Number of pods to load balance between
  replicas: 1

image:
  # -- image repository
  repository: mikenye/radarbox
  # -- image tag
  tag: "v1.0.7-20220512134600"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [application docs](https://flightaware.com/adsb/piaware/advanced_configuration) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

autoscaling:
  enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

securityContext:
  # -- (bool) Privileged securityContext may be required if USB device is accessed directly through the host machine
  privileged: false

serviceAccount:
  # Specifies whether a service account should be created
  create: false
